language: node_js
sudo: false
node_js:
- stable
- lts/*
cache: yarn
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "${HOME}/.npmrc"
- npm whoami
jobs:
  include:
    - stage: test
      script: yarn run test
deploy:
- provider: script
  script: yarn run release
  skip_cleanup: true
  on:
    repo: taka-sho/lint-configs
    tags: true
notifications:
  email: false
